sudo: required
dist: trusty
language: generic

env:
  global:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true
    - NOT_TEST_INSTALL=true
    
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"

matrix:
  allow_failures:
    - env: ROS_DISTRO="lunar"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
